version: "3.9"

services:
  orders-mongo:
    image: "mongo:7.0.8"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_ORDERS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME_ORDERS}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD_ORDERS}
    ports:
      - 27017:27017

  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@orders-mongo:27017/
      ME_CONFIG_BASICAUTH: false
